version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookshelf-api
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
